### ISSUE TITLE
Remove (or ?) backtick from message

### ISSUE THREAD

**Issue by roncewind** [Senzing/senzing-tools#109]
On this line: 

https://github.com/Senzing/senzing-tools/blob/main/cmd/root.go#L91

There is a backtick instead of a single quote or use a backtick after the the command so that it is properly formatted for a markdown like inline code block?

Bigger question is should we be using Fprintf to stderr at all?  This would ruin any JSON output.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/senzing-tools/pull/111
