### ISSUE TITLE
Error help/explanation

### ISSUE THREAD

**Issue by roncewind** [Senzing/senzing-tools#38]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I get an error message and I don't know how to fix it, or what it means.

**Describe the solution you'd like**
How about a tool `senzing-tools explain --error senzing-73451234` which would show me the error message, so I can verify that it's the same error AND (more importantly) suggest why this may have happen with possible ways to rectify the error.

**Describe alternatives you've considered**
The alternative is that I search the internet and hopefully find the error message OR (and more likely) I open a support ticket so support can tell me how to fix the error.

**Comment by docktermj** [comment]
Implemented via https://github.com/Senzing/explain/issues/3

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/senzing-tools/pull/80
